[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/medical-transcription"
  to = "/.netlify/functions/medical-transcription"
  status = 200

[[headers]]
  for = "/"
  [headers.values]
    X-Robots-Tag = "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"
    
[[headers]]
  for = "/*.html"
  [headers.values]
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
